<?php

namespace AppBundle\Repository;

/**
 * ArquivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArquivoRepository extends \Doctrine\ORM\EntityRepository
{
}
