<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Tipo;

/**
 * ArquivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArquivoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTes()
    {
        return '54';
    }
//    public function buscarDidicionarioDados(Tipo $tipo, int $ano)
//    {
//        return $this->findOneBy(['tipo' => $tipo, 'ano' => $ano]);
//    }

}
