<?php

namespace AppBundle\Repository;

/**
 * ExameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExameRepository extends \Doctrine\ORM\EntityRepository
{
}
