# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    carga:
        class: AppBundle\Utils\Carga
        arguments: ["@service_container"]

    extracao:
        class: AppBundle\Utils\Extracao
        arguments: ["@service_container"]

    descarga:
        class: AppBundle\Utils\Descarga
        arguments: ["@service_container"]

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
